///|
pub type SourceFileKind = @model.SourceFileKind

///|
pub type SourceFile = @model.SourceFile

///|
pub type ProjectRoot = @model.ProjectRoot

///|
pub type Project = @model.Project

///|
pub type EmbedOption = @model.EmbedOption

///|
pub type LinkDirective = @model.LinkDirective

///|
pub type EmbedDirective = @model.EmbedDirective

///|
pub type RichContentDirective = @model.RichContentDirective

///|
pub type RichContentChunk = @model.RichContentChunk

///|
pub type RichContent = @model.RichContent

///|
pub type Metadata = @model.Metadata

///|
pub type ParsedTree = @model.ParsedTree

///|
pub type SourceFileDependencyKind = @model.SourceFileDependencyKind

///|
pub type SourceFileDependency = @model.SourceFileDependency

///|
pub type DanglingTreeLink = @model.DanglingTreeLink

///|
pub type CompiledTree = @model.CompiledTree

///|
pub type CompiledProject = @model.CompiledProject

///|
pub type PreviewResult = @model.PreviewResult

///|
pub type TreeSlug = @model.TreeSlug

///|
pub type TaxonKey = @model.TaxonKey

///|
pub type Taxon = @model.Taxon
